#!/usr/bin/env bash
set -euo pipefail

# test-pullemit-capture.sh — v0.8.0 [E] STEP E3 (club-3090 #141 / #147).
#
# Contract test for CONTRACT-4 (E3 half): the derived BOOT stage
# (HF_HOME host->container mount, NOT MODEL_DIR), the capability-aware
# DERIVED smoke prober (the conservative floor), and the 4 §6 capture-point
# artifact emitters + the §6.2/§6.3 manifest. The test IS the spec; the code
# is fixed to it. NO live Docker / GPU / network — an injected fixture
# runner + fixture client; artifacts written to a real tmp repo root and
# grepped on disk for redaction.
#
# Coverage:
#   * E3/E4-fix: booted_derived is a CONTEXT MANAGER — boot success yields
#     a live BootResult.ok handle WHILE the server is UP (smoke runs inside
#     the `with`, NOT after teardown); teardown (down) happens on __exit__
#     AFTER the with-body. Proves up -> (smoke, server alive) -> down, and
#     that teardown STILL runs if the with-body raises (on-rig E5 caught
#     the prior teardown-in-finally-before-smoke -> ConnectionRefused).
#   * boot container-died (fixture runner) -> ok=False handle STILL yielded
#     (CM does NOT raise for an expected boot failure), teardown STILL
#     invoked on __exit__ (always-teardown discipline at the CM scope).
#   * boot uses the HF_HOME host->container :ro mount carried in
#     compose_text (NOT MODEL_DIR); --project-directory discipline.
#   * smoke floor: plain-chat + streaming ALWAYS probed; a config declaring
#     NO tools -> tool-call:"unsmoked", partial:true; a config declaring
#     tools -> tool-call actually smoked.
#   * all 4 artifacts written with EXACT CONTRACT-4 schema/keys (pt1 gate /
#     pt2 download / pt3 boot / pt4 smoke), schema:1.
#   * manifest: §6.2 consensus-key fields FIRST-CLASS (asserted present at
#     top level, not only hashed) + submission_fingerprint present +
#     topology_summary_canonical present + §6.3 dedup inputs first-class
#     with failure_class == null (E3 does NOT classify).
#   * CAPTURE-POINT 5 NOT emitted (out of E3 scope).
#   * redaction asserted: no /opt/ai, no $HF_TOKEN value, no host/user in
#     ANY written artifact (grep the files on disk).

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT_DIR"
export PYTHONPATH="$ROOT_DIR${PYTHONPATH:+:$PYTHONPATH}"

python3 - "$ROOT_DIR" <<'PY'
from __future__ import annotations

import json
import sys
import tempfile
from pathlib import Path
from types import SimpleNamespace

root = Path(sys.argv[1])
sys.path.insert(0, str(root))

from scripts.lib.profiles import booter as B          # noqa: E402
from scripts.lib.profiles import capture as C          # noqa: E402
from scripts.lib.profiles.downloader import DownloadResult  # noqa: E402
from scripts.lib.profiles.einput import EInput         # noqa: E402

failures: list[str] = []


def check(cond: bool, msg: str) -> None:
    if cond:
        print(f"PASS: {msg}")
    else:
        print(f"FAIL: {msg}", file=sys.stderr)
        failures.append(msg)


# ---------------------------------------------------------------------------
# A representative E1-emitted derived compose body. The load-bearing line for
# E3 is the HF_HOME host->container :ro volume (NOT MODEL_DIR).
# ---------------------------------------------------------------------------
COMPOSE_TEXT = (
    "# GENERATED by scripts/pull.sh — club-3090 [E] derived-vllm\n"
    "services:\n"
    "  vllm-derived-org-my-model:\n"
    "    image: vllm/vllm-openai:nightly-deadbeef\n"
    "    volumes:\n"
    "      - /data/hf/club3090/pulls/org-my-model:"
    "/models/club3090/pulls/org-my-model:ro\n"
    "    environment:\n"
    "      - NVIDIA_VISIBLE_DEVICES=0\n"
    "      - HUGGING_FACE_HUB_TOKEN=${HF_TOKEN:-}\n"
)


def mk_einput(slug, *, der, terminal="proceed"):
    return EInput(
        slug=slug, terminal=terminal, is_override_accepted=False, der=der,
        runtime={"engine": "vllm-nightly-clean", "kv_format": "bf16",
                 "tp": 1, "max_ctx": 131072, "default_port": 8071},
        selected_files=[], hf_home=Path("/data/hf"), c2a=None,
        hardware_sm=8.6, visible_gpu_count=1, per_gpu_vram_mib=[24576],
        selected_gpu_indices=[0], selected_gpu_vram_mib=[24576],
        topology_summary="[(RTX 3090, 24576)]", club3090_commit="deadbeef",
        diagnostics={},
    )


# ---------------------------------------------------------------------------
# Fixture runner: records up/wait_ready/down (and test-injected "smoke")
# calls in invocation order; can simulate a dead container by raising
# BootError from up() or wait_ready(). With booted_derived (a CM), down()
# is only invoked on __exit__ — AFTER the `with` body — so the recorded
# order proves up -> (smoke while UP) -> down.
# ---------------------------------------------------------------------------
class FixtureRunner:
    def __init__(self, *, die_on="", reason=""):
        self.die_on = die_on
        self.reason = reason
        self.calls: list[tuple[str, str, str]] = []

    def up(self, project_dir, compose_path):
        self.calls.append(("up", project_dir, compose_path))
        # Assert the proven HF_HOME mount is present in the written compose
        # (NOT MODEL_DIR) and the project dir is a real isolated dir.
        body = Path(compose_path).read_text()
        assert "/models/club3090/pulls/" in body and ":ro" in body, \
            "compose missing HF_HOME host->container :ro mount"
        assert "MODEL_DIR" not in body, "derived boot must NOT use MODEL_DIR"
        assert Path(project_dir).is_dir(), "project dir must exist for --project-directory"
        if self.die_on == "up":
            raise B.BootError(self.reason or "container exited (code 1)")

    def wait_ready(self, endpoint):
        self.calls.append(("wait_ready", endpoint, ""))
        if self.die_on == "wait_ready":
            raise B.BootError(self.reason or "container died before ready")

    def down(self, project_dir, compose_path):
        self.calls.append(("down", project_dir, compose_path))


# ---------------------------------------------------------------------------
# 1. E3/E4-fix — booted_derived is a CONTEXT MANAGER. Boot success ->
#    BootResult.ok handle yielded WHILE the server is UP; smoke runs INSIDE
#    the `with` (server alive, NOT torn down); teardown (down) happens on
#    __exit__, AFTER the with-body. This is the assertion that proves the
#    on-rig E5 teardown-in-finally-before-smoke -> ConnectionRefused
#    root-cause is fixed (prior boot_derived tore down before returning).
# ---------------------------------------------------------------------------
der_plain = SimpleNamespace(profile={"arch": "LlamaForCausalLM",
                                      "weight_format": "bfloat16"})
ei = mk_einput("org/My-Model", der=der_plain)
r = FixtureRunner()
with B.booted_derived(ei, COMPOSE_TEXT, runner=r) as res:
    # INSIDE the with-body: server is UP. down() must NOT have run yet.
    check(res.ok is True and res.failure is None,
          f"boot success: BootResult.ok handle yielded "
          f"(got ok={res.ok} fail={res.failure})")
    check(res.endpoint == "http://127.0.0.1:8071/v1",
          f"boot success: endpoint on host-published port "
          f"(got {res.endpoint})")
    _evs = [c[0] for c in r.calls]
    check("up" in _evs and "wait_ready" in _evs,
          "boot success: up + wait_ready invoked before the handle is "
          "yielded")
    check("down" not in _evs,
          "E3/E4-fix: teardown (down) has NOT run yet INSIDE the `with` — "
          "the server is ALIVE for smoke+capture (the on-rig E5 fix)")
    # Simulate the orchestrator smoking the LIVE server inside the body.
    r.calls.append(("smoke", res.endpoint, ""))
# <- CM __exit__ HERE.
_ev = [c[0] for c in r.calls]
check(_ev[-1] == "down",
      f"boot success: teardown (down) ALWAYS invoked LAST, on __exit__, "
      f"AFTER the with-body smoke (calls={_ev})")
check(_ev.index("down") > _ev.index("smoke") > _ev.index("up"),
      f"boot success: order is up -> ... -> smoke -> down (teardown idx > "
      f"smoke idx > up idx) (calls={_ev})")
# Snapshot the (now torn-down) handle for the §4 capture test reuse — the
# capture test only reads .ok/.seconds/.failure (a value object, valid
# post-exit).
res_snapshot = B.BootResult(ok=res.ok, seconds=res.seconds,
                            failure=res.failure, endpoint=res.endpoint)
res = res_snapshot

# ---------------------------------------------------------------------------
# 2. Boot container-died -> ok=False handle STILL yielded (CM does NOT raise
#    for an EXPECTED boot failure — orchestrator must still emit pt3 +
#    capture) + teardown STILL invoked on __exit__.
# ---------------------------------------------------------------------------
r2 = FixtureRunner(die_on="wait_ready", reason="CUDA OOM; worker exited")
with B.booted_derived(ei, COMPOSE_TEXT, runner=r2) as res2:
    check(res2.ok is False and res2.failure == "CUDA OOM; worker exited",
          f"boot died: ok=False handle YIELDED (not raised) + failure "
          f"populated (got ok={res2.ok} fail={res2.failure!r})")
    check(res2.endpoint is None, "boot died: endpoint None on failure")
    check("down" not in [c[0] for c in r2.calls],
          "boot died: teardown deferred to __exit__ (still inside `with`)")
check("down" in [c[0] for c in r2.calls]
      and [c[0] for c in r2.calls][-1] == "down",
      "boot died: teardown STILL invoked on __exit__ (always-teardown "
      "discipline preserved at the CM scope)")

r3 = FixtureRunner(die_on="up", reason="image pull failed")
with B.booted_derived(ei, COMPOSE_TEXT, runner=r3) as res3:
    check(res3.ok is False and "image pull failed" in (res3.failure or ""),
          f"boot up-fail: ok=False handle yielded, failure surfaced "
          f"(got {res3.failure!r})")
check("down" in [c[0] for c in r3.calls],
      "boot up-fail: teardown STILL invoked on __exit__")

# 2b. E3/E4-fix — teardown STILL runs if the `with` BODY raises (the CM's
#     finally fires on the exceptional __exit__; no orphan ever).
r4 = FixtureRunner()
_raised = False
try:
    with B.booted_derived(ei, COMPOSE_TEXT, runner=r4) as res4:
        check(res4.ok is True, "boot exc-body: server up before body raises")
        check("down" not in [c[0] for c in r4.calls],
              "boot exc-body: down not run yet (inside body)")
        raise RuntimeError("orchestrator-body blew up mid-with")
except RuntimeError:
    _raised = True
check(_raised, "boot exc-body: the with-body exception still propagates")
check([c[0] for c in r4.calls][-1] == "down",
      "boot exc-body: CM teardown STILL ran on the exceptional __exit__ "
      "(no-orphan guarantee preserved even when the body raises)")

# ---------------------------------------------------------------------------
# 3. Smoke floor: plain-chat + streaming ALWAYS; no-tools -> unsmoked/partial.
# ---------------------------------------------------------------------------
class FixtureClient:
    # Lock-step with the E3-fix probe signature: smoke_derived now passes
    # the resolved served-model-name as a 3rd arg (NOT the literal
    # "derived"). The fixture records it so the test can assert it.
    def __init__(self, green=True):
        self.green = green
        self.probed: list[str] = []
        self.models: list[str] = []

    def probe(self, capability, endpoint, model_name):
        self.probed.append(capability)
        self.models.append(model_name)
        return self.green


# config declares NO optional capabilities -> floor only.
fc = FixtureClient(green=True)
sm = C.smoke_derived(ei, "http://127.0.0.1:8071/v1", client=fc)
check(set(fc.probed) == {"plain-chat", "streaming"},
      f"smoke floor: ONLY plain-chat+streaming probed when nothing declared "
      f"(probed={sorted(fc.probed)})")
check(sm.results["plain-chat"] == "green"
      and sm.results["streaming"] == "green",
      "smoke floor: plain-chat + streaming green")
check(sm.results["tool-call"] == "unsmoked",
      "smoke floor: undeclared tool-call -> 'unsmoked'")
check(all(sm.results[c] == "unsmoked" for c in
          ("tool-call", "reasoning-streaming", "structured-output",
           "vision", "long-context")),
      "smoke floor: every undeclared optional cap -> 'unsmoked'")
check(sm.partial is True,
      "smoke floor: partial:true when any capability un-smoked (§6.2)")
check(sm.smoke_capability_set == ["plain-chat", "streaming"],
      f"smoke floor: smoke_capability_set == floor (got {sm.smoke_capability_set})")

# config POSITIVELY declares tool-call -> tool-call actually smoked.
der_tools = SimpleNamespace(profile={
    "arch": "LlamaForCausalLM", "weight_format": "bfloat16",
    "config": {"tool_use": True},
})
ei_t = mk_einput("org/Tooly", der=der_tools)
fc2 = FixtureClient(green=True)
sm2 = C.smoke_derived(ei_t, "http://x/v1", client=fc2)
check("tool-call" in fc2.probed,
      "smoke declared: tool-call IS probed when config declares it")
check(sm2.results["tool-call"] == "green",
      "smoke declared: declared tool-call -> green (probed, not unsmoked)")
check("tool-call" in sm2.smoke_capability_set,
      "smoke declared: tool-call in smoke_capability_set")
check(sm2.partial is True,
      "smoke declared: still partial (vision/etc undeclared -> unsmoked)")

# red probe -> recorded red (not unsmoked).
fc3 = FixtureClient(green=False)
sm3 = C.smoke_derived(ei, "http://x/v1", client=fc3)
check(sm3.results["plain-chat"] == "red" and sm3.results["streaming"] == "red",
      "smoke red: a failing floor probe records 'red' (caught #145 class)")

# ---------------------------------------------------------------------------
# 3b. E3-fix: the probe MUST send the real served-model-name (NOT the literal
#     "derived") + a non-200 produces red WITH the additive status/error
#     detail. This is the on-rig E5 defect: healthy boot, model:"derived" is
#     an unknown served name -> vLLM 404 -> every floor probe red.
# ---------------------------------------------------------------------------
from scripts.lib.profiles.downloader import sanitize_slug as _san  # noqa: E402

# (i) smoke_derived passes the resolved served-model-name to the client.
fc_name = FixtureClient(green=True)
C.smoke_derived(ei, "http://127.0.0.1:8071/v1", client=fc_name)
expected_name = _san(ei.slug)  # == generate_from_profile --served-model-name
check(expected_name == "org-my-model",
      f"E3-fix: sanitize_slug(slug) == emitted served-model-name "
      f"(got {expected_name!r})")
check(set(fc_name.models) == {expected_name},
      f"E3-fix: probe receives the REAL served-model-name, not 'derived' "
      f"(got {sorted(set(fc_name.models))})")
check("derived" not in fc_name.models,
      "E3-fix: the literal 'derived' is NEVER sent as the model field")

# (ii) compose_meta.served_model_name (priority a) overrides the slug fallback.
fc_meta = FixtureClient(green=True)
C.smoke_derived(ei, "http://x/v1", client=fc_meta,
                compose_meta={"served_model_name": "qwen-qwen2.5-0.5b-instruct"})
check(set(fc_meta.models) == {"qwen-qwen2.5-0.5b-instruct"},
      f"E3-fix: compose_meta.served_model_name is authoritative (priority a) "
      f"(got {sorted(set(fc_meta.models))})")

# (iii) the REAL _HttpSmokeClient builds the body with the real model name
#       (request-building unit; NO network — _build_body is factored out).
real = C._HttpSmokeClient()
b_plain = real._build_body("plain-chat", expected_name)
check(b_plain["model"] == expected_name and b_plain["model"] != "derived",
      f"E3-fix: real client body model=='{expected_name}' not 'derived' "
      f"(got {b_plain['model']!r})")
check(b_plain.get("stream") is None,
      "E3-fix: plain-chat body has no stream flag")
b_str = real._build_body("streaming", expected_name)
check(b_str["model"] == expected_name and b_str.get("stream") is True,
      "E3-fix: streaming body keeps stream:true + real model name")

# (iv) a simulated non-200 -> red WITH the additive status/error detail.
class Fixture404Client:
    def probe(self, capability, endpoint, model_name):
        # mirrors _HttpSmokeClient's (ok, status, error) contract on a 404.
        return (False, 404,
                f'HTTP 404: {{"object":"error","message":'
                f'"The model `{model_name}` does not exist."}}')

sm404 = C.smoke_derived(ei, "http://x/v1", client=Fixture404Client())
check(sm404.results["plain-chat"] == "red"
      and sm404.results["streaming"] == "red",
      "E3-fix: non-200 floor probe -> red (the on-rig red-smoke symptom)")
check(sm404.results_detail.get("plain-chat", {}).get("status") == 404
      and "does not exist" in
          sm404.results_detail.get("plain-chat", {}).get("error", ""),
      f"E3-fix: red carries additive {{status:404, error:...}} detail "
      f"(got {sm404.results_detail.get('plain-chat')!r})")
check("streaming" in sm404.results_detail
      and sm404.results_detail["streaming"]["status"] == 404,
      "E3-fix: every failing capability gets a results_detail entry")
# green caps carry NO detail (additive only on red).
sm_green = C.smoke_derived(ei, "http://x/v1", client=FixtureClient(green=True))
check(sm_green.results_detail == {},
      "E3-fix: results_detail empty when nothing is red (additive-on-red)")

# (v) legacy 2-arg fixture client still works (injected-seam compatibility).
class LegacyClient:
    def __init__(self):
        self.calls = 0
    def probe(self, capability, endpoint):  # OLD signature
        self.calls += 1
        return True

lc = LegacyClient()
sm_legacy = C.smoke_derived(ei, "http://x/v1", client=lc)
check(lc.calls >= 2 and sm_legacy.results["plain-chat"] == "green",
      "E3-fix: legacy 2-arg client still accepted (seam not weakened)")

# ---------------------------------------------------------------------------
# 4. The 4 artifacts + manifest: EXACT CONTRACT-4 schema/keys, redacted.
# ---------------------------------------------------------------------------
dl = DownloadResult(ok=True, files=["model.safetensors", "config.json"],
                    bytes=11_000_000_000, sha_verified=True, failure=None,
                    local_dir="/data/hf/club3090/pulls/org-my-model")
compose_meta = {
    "resolved_image": "vllm/vllm-openai:nightly-deadbeef",
    "max_model_len": 131072, "kv_format": "bf16",
    "engine": "vllm-nightly-clean",
}

with tempfile.TemporaryDirectory() as td:
    out = C.emit_capture(
        ei,
        confidence=SimpleNamespace(name="ESTIMATED_LOWER_BOUND"),
        raw_verdict="fits-clean",
        profile_like="vllm/gemma-a4b-single",
        download_result=dl,
        boot_result=res,
        smoke_result=sm,
        compose_meta=compose_meta,
        kv_calc_version="kvcalc-v7",
        repo_root=Path(td),
        ts="20260517T120000Z",
    )
    p = out["paths"]

    pt1 = json.loads(Path(p["gate"]).read_text())
    check(pt1 == {
        "schema": 1, "point": "gate", "slug": "org/My-Model",
        "confidence": "ESTIMATED_LOWER_BOUND", "raw_verdict": "fits-clean",
        "terminal": "proceed", "profile_like": "vllm/gemma-a4b-single",
        "hardware_sm": 8.6,
    }, f"pt1 gate EXACT CONTRACT-4 schema/keys (got {sorted(pt1)})")

    pt2 = json.loads(Path(p["download"]).read_text())
    check(pt2 == {
        "point": "download", "ok": True,
        "files": ["model.safetensors", "config.json"],
        "bytes": 11_000_000_000, "sha_verified": True, "failure": None,
    }, f"pt2 download EXACT CONTRACT-4 (E2 DownloadResult shape) "
       f"(got {sorted(pt2)})")

    pt3 = json.loads(Path(p["boot"]).read_text())
    check(set(pt3) == {"point", "ok", "seconds", "failure"}
          and pt3["point"] == "boot" and pt3["ok"] is True
          and pt3["failure"] is None,
          f"pt3 boot EXACT CONTRACT-4 (got {sorted(pt3)})")

    pt4 = json.loads(Path(p["smoke"]).read_text())
    # LOCKED CONTRACT-4 keys unchanged; `results_detail` is the ONLY
    # additive field (E3-fix). Assert the locked shape/values explicitly +
    # that the additive key is present (tightened, never weakened).
    check(set(pt4) == {"point", "smoke_capability_set", "results",
                       "partial", "results_detail"}
          and pt4["point"] == "smoke"
          and pt4["smoke_capability_set"] == ["plain-chat", "streaming"]
          and pt4["partial"] is True
          and pt4["results"]["tool-call"] == "unsmoked",
          f"pt4 smoke CONTRACT-4 locked keys + additive results_detail "
          f"(got {sorted(pt4)})")
    check(pt4["results"]["plain-chat"] == "green"
          and pt4["results"]["streaming"] == "green",
          "pt4 smoke: locked `results` byte-behaviour-unchanged (green floor)")
    check(isinstance(pt4["results_detail"], dict),
          "pt4 smoke: results_detail is an (additive) dict")

    # CAPTURE-POINT 5 NOT emitted (out of E3 scope).
    cap_dir = Path(out["dir"])
    files = sorted(x.name for x in cap_dir.iterdir())
    check(files == ["manifest.json", "pt1-gate.json", "pt2-download.json",
                    "pt3-boot.json", "pt4-smoke.json"],
          f"only pt1-4 + manifest written; NO pt5/override_capture "
          f"(got {files})")
    check(not any("override" in f for f in files),
          "CAPTURE-POINT 5 (override-accepted force-capture) NOT emitted (E4)")

    # ---- manifest: consensus-key fields FIRST-CLASS + failure_class null --
    man = json.loads(Path(p["manifest"]).read_text())
    for k in ("model", "quant_label", "arch_family", "topology_class",
              "engine_pin", "engine_version", "kv_calc_version",
              "selected_ctx", "kv_format", "smoke_capability_set",
              "topology_summary_canonical", "submission_fingerprint",
              "model_id", "failure_class"):
        check(k in man,
              f"manifest: §6.2/§6.3 key {k!r} is FIRST-CLASS (top level, "
              f"not only hashed)")
    check(man["model"] == "org/My-Model"
          and man["quant_label"] == "bfloat16"
          and man["arch_family"] == "LlamaForCausalLM"
          and man["engine_pin"] == "vllm/vllm-openai:nightly-deadbeef"
          and man["kv_calc_version"] == "kvcalc-v7"
          and man["selected_ctx"] == 131072
          and man["kv_format"] == "bf16"
          and man["smoke_capability_set"] == ["plain-chat", "streaming"]
          and man["topology_summary_canonical"] == "[(RTX 3090, 24576)]",
          "manifest: consensus-key values populated from einput/compose_meta")
    check(man["failure_class"] is None,
          "manifest: failure_class is NULL — E3 must NOT classify "
          "(§6.1 = [F]'s job)")
    check(isinstance(man["submission_fingerprint"], str)
          and len(man["submission_fingerprint"]) == 64,
          "manifest: submission_fingerprint is the §6.2 H(...) hash")

    # ---- redaction: NO path/token/host/user leak in ANY artifact --------
    import os
    import subprocess
    user = os.environ.get("USER") or ""
    host = subprocess.run(["hostname", "-s"], capture_output=True,
                          text=True).stdout.strip()
    for art in p.values():
        blob = Path(art).read_text()
        check("/opt/ai" not in blob,
              f"redaction: no /opt/ai path leak in {Path(art).name}")
        check("HF_TOKEN=" not in blob or "HF_TOKEN=<REDACTED>" in blob
              or "HF_TOKEN=" not in blob,
              f"redaction: no raw HF_TOKEN value in {Path(art).name}")
        check("hf_" not in blob or "hf_<REDACTED>" in blob
              or not any(seg.startswith("hf_") and len(seg) > 33
                         for seg in blob.split()),
              f"redaction: no hf_ token in {Path(art).name}")
        if user and user not in ("root",):
            check(f"/home/{user}" not in blob,
                  f"redaction: no /home/{user} in {Path(art).name}")
        if host:
            check(host not in blob or host == "<HOST>",
                  f"redaction: no bare hostname in {Path(art).name}")

    # A redaction smoke: an einput carrying a leaky path/token gets scrubbed.
    leaky = mk_einput("org/Leaky",
                      der=SimpleNamespace(profile={
                          "arch": "/opt/ai/secret",
                          "weight_format": "bfloat16"}))
    out2 = C.emit_capture(
        leaky, confidence=SimpleNamespace(name="EXACT"),
        raw_verdict="fits-clean", profile_like="vllm/x",
        download_result=dl, boot_result=res, smoke_result=sm,
        compose_meta=compose_meta, kv_calc_version="kvcalc-v7",
        repo_root=Path(td), ts="20260517T130000Z",
    )
    for art in out2["paths"].values():
        check("/opt/ai" not in Path(art).read_text(),
              f"redaction: leaky /opt/ai scrubbed from {Path(art).name}")

if failures:
    print(f"\n{len(failures)} assertion(s) failed.", file=sys.stderr)
    sys.exit(1)
print("\nAll E3 boot + smoke + capture (CONTRACT-4) assertions passed.")
PY

echo "test-pullemit-capture.sh OK"
